stages:
  - build
  - deploy

variables:
  SHORT_NAME: search
  CI_REGISTRY_IMAGE: dockerhub.mingas.by/${SHORT_NAME}

build-job:
  stage: build
  only:
    - main
  tags:
    - search
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker pull $CI_REGISTRY_IMAGE:latest-migrate || true
    - docker build -f ./docker/Dockerfile --target runner --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest -t ${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA .
    - docker build -f ./docker/Dockerfile --target migrate --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest-migrate -t ${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA-migrate .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-migrate
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-migrate $CI_REGISTRY_IMAGE:latest-migrate
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest-migrate
    - docker system prune -a -f

deploy-job:
  stage: deploy
  needs:
    - build-job
  only:
    - main
  tags:
    - search
  script:
    - docker compose --env-file "$ENV_FILE" config -q
    - docker compose --env-file "$ENV_FILE" --profile migrate run --rm migrate
    - docker compose --env-file "$ENV_FILE" up -d
    - docker system prune -a -f
  environment:
    name: prod
