services:

    migrate:
        image: ${CI_REGISTRY_IMAGE_MIGRATE}:${CI_COMMIT_SHORT_SHA}
        container_name: migrate
        env_file:
            - $ENV_FILE
        profiles:
            - migrate
        environment:
            DATABASE_URL: ${DATABASE_URL}
        depends_on:
            postgres:
                condition: service_healthy
        restart: no

    app:
        image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
        restart: unless-stopped
        container_name: nest_app
        pull_policy: always
        command: ["node", "dist/main.js"]

        env_file:
            - $ENV_FILE

        environment:
            NODE_ENV: production
            HOST: 0.0.0.0
            PORT: ${PORT}
            DATABASE_URL: ${DATABASE_URL}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            GOTENBERG_URL: http://${GOTENBERG_HOST}:${GOTENBERG_PORT}
            LDAP_HOST: ${LDAP_HOST}
            LDAP_PORT: ${LDAP_PORT}
            LDAP_BASEDN: ${LDAP_BASE_DN}
            LDAP_ADMIN_DN: ${LDAP_ADMIN_DN}
            LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}

        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            elasticsearch:
                condition: service_started
            gotenberg:
                condition: service_started
        networks:
            - default
            - search_network
    

    postgres:
        image: dockerhub.mingas.by/postgres:15.2
        restart: unless-stopped
        container_name: postgres
        env_file:
            - $ENV_FILE
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: Search

        ports:
            - 15432:5432

        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d

        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d Search']
            interval: 5s
            timeout: 3s
            retries: 10

    redis:
        image: dockerhub.mingas.by/redis:7.0.5-alpine
        restart: unless-stopped
        container_name: redis-art
        env_file:
            - $ENV_FILE
        
        ports:
            - 16379:6379

        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 3s
            timeout: 3s
            retries: 10

    elasticsearch:
        image: dockerhub.mingas.by/elasticsearch:elastic-pluggin
        restart: unless-stopped
        container_name: elasticsearch
        env_file:
            - $ENV_FILE
       

        environment:
            - node.name=${ELASTIC_NODE_NAME}
            - cluster.name=${CLUSTER_NAME}
            - discovery.type=single-node
            - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - xpack.security.enabled=true
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m


        volumes:
            - esdata:/usr/share/elasticsearch/data

    gotenberg:
        image: dockerhub.mingas.by/gotenberg:8
        restart: unless-stopped
        container_name: gotenberg
        env_file:
            - $ENV_FILE

volumes:
    pgdata:
    esdata:

networks:
    search_network:
        external: true
