FROM node:20-alpine


RUN apk add --no-cache openssl bash
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma


RUN npm install && npx prisma generate


COPY . .


EXPOSE 3000

CMD ["npm", "run", "start:dev"]

