services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev

    container_name: nest_app

    env_file:
      - .env

    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000

      # hot reload (обязательно для Docker + Windows)
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_INTERVAL: 1000

      DATABASE_URL: postgres://postgres:postgres@postgres:5432/Search?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GOTENBERG_URL: http://gotenberg:3000
      LDAP_HOST: openldap
      LDAP_PORT: 389
      LDAP_BASEDN: dc=mycompany,dc=local
      LDAP_ADMIN_DN: cn=admin,dc=mycompany,dc=local
      LDAP_ADMIN_PASSWORD: admin

    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./uploads:/app/uploads

    ports:
      - "3000:3000"
      - "5555:5555"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      openldap:
        condition: service_started
      gotenberg:
        condition: service_started

    command: npm run start:dev

    networks:
      - appnet

  postgres:
    image: postgres:15-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Search

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Search" ]
      interval: 5s
      timeout: 3s
      retries: 10

    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis

    ports:
      - "6379:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 10

    networks:
      - appnet

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile

    env_file:
      - .env

    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "${ELASTICSEARCH_PORT}:9200"

    volumes:
      - esdata:/usr/share/elasticsearch/data

    networks:
      - appnet

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap

    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "mycompany.local"
      LDAP_ADMIN_PASSWORD: admin

    ports:
      - "389:389"

    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

    networks:
      - appnet

  phpldapadmin:
    image: osixia/phpldapadmin:0.8.0
    container_name: phpldapadmin

    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"

    ports:
      - "8080:80"

    depends_on:
      - openldap

    networks:
      - appnet

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg

    ports:
      - "3001:3000"

    networks:
      - appnet

volumes:
  pgdata:
  node_modules:
  esdata:
  ldap_data:
  ldap_config:


networks:
  appnet:
    driver: bridge
