FROM dockerhub.mingas.by/node:22-alpine

RUN apk add --no-cache openssl libc6-compat

WORKDIR /app

RUN npm install prisma@6.19.3 && npm cache clean --force

COPY prisma ./prisma


CMD ["npx", "prisma", "migrate", "deploy"]
