FROM dockerhub.mingas.by/node:22-slim



RUN apt-get update \

    && apt-get install -y --no-install-recommends openssl ca-certificates \

    && rm -rf /var/lib/apt/lists/*



WORKDIR /app

RUN npm install prisma@6.19.3 && npm cache clean --force

COPY prisma ./prisma


CMD ["npx", "prisma", "migrate", "deploy"]
