FROM node:20-alpine

RUN apk add --no-cache bash openssl

WORKDIR /app

# только зависимости
COPY package*.json ./
COPY prisma ./prisma

RUN npm ci

COPY . .

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_INTERVAL=1000

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
